# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d26fe172d08e481563bbab652e080cb8500d820f0023ac1178f2322dc3dbb7135e163160fc03b14a405cdda4447d9067758124f5731b5c5960ea9711f8c655b7

test:
  secret_key_base: 466656ae1df9da7b6bde084f2861b691fa07b9e0cd1bd52d148b4ee7d6cd01c5e1c77b37858ea40a7a06b45a6e8e03493d7b1aa5de0f6328ec6241216e61adb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
